# GENERATE TIME: Sun Feb 12 23:02:19 2023
# CMD:
# basicsr/train.py -opt options/train/EDSR/train_EDSR_Lx4.yml

# GENERATE TIME: Thu Feb  9 03:49:40 2023
# CMD:
# basicsr/train.py -opt options/train/EDSR/train_EDSR_Lx4.yml

# GENERATE TIME: Thu Feb  9 03:17:59 2023
# CMD:
# basicsr/train.py -opt options/train/EDSR/train_EDSR_Lx4.yml

# GENERATE TIME: Tue Feb  7 13:04:04 2023
# CMD:
# basicsr/train.py -opt options/train/EDSR/train_EDSR_Lx4.yml

# general settings
name: RDNbest_2times_patch_64_groundnew_
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: D:\SR\DIV2K_train_HR
      #D:\Project\DATA\DIV2K\benchmark\DIV2K_train_HR
    dataroot_lq: D:\SR\X2_1024
      #D:\Project\DATA\DIV2K\benchmark\X4
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 64
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 12
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    # dataroot_gt: D:\Project\DATA\DIV2K\benchmark\Div2k10\HR
    # dataroot_lq: D:\Project\DATA\DIV2K\benchmark\Div2k10\LR_bicubic\X4
    dataroot_gt: D:\SR\Set5\HR
    dataroot_lq: D:\SR\Set5\X2
    io_backend:
      type: disk

# network structures
network_g:
  type: EDSR
  # num_in_ch: 3
  # num_out_ch: 3
  # num_feat: 64
  # num_group: 10
  # num_block: 20
  # squeeze_factor: 16
  # upscale: 4
  # res_scale: 1
  # img_range: 255
  # rgb_mean: [0.4488, 0.4371, 0.4040]
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 16
  num_block: 32
  upscale: 2
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]


# path
path:
  pretrain_network_g: D:\SR\BasicSR\experiments\RDNbest_2times_patch_400_groundnew\models\net_g_6000.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [40000,80000,120000]
    gamma: 0.5
  # scheduler:
  #   type: CosineAnnealingRestartLR
  #   periods: [10000,10000,10000,10000,10000,10000,10000,10000,10000,10000]
  #   restart_weights: [1,1,1,1,1,1,1,1,1,1]
  #   eta_min: !!float 1e-6

  total_iter: 140000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 1000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq:  1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
